version: 1.0.{build}
image: ubuntu
stack: node 8

build_script:
    - npm install
    - npm run lint
    - npm run build

after_build:
    - npm prune --production
    - rm -rf .git .vscode .gitignore .prettierignore .prettierrc README.md tsconfig.json tslint.json

artifacts:
    - path: /
      name: Halcyon.Api
      type: Zip

deploy:
    - provider: Environment
      name: halcyon-node-api
