version: 1.0.{build}
image: ubuntu
stack: node 8

build_script:
- yarn
- yarn lint

after_build:
- yarn --production
- rm -rf .git .vscode .gitignore README.md tsconfig.json tslint.json

artifacts:
- path: /
  name: Halcyon.Api
  type: Zip
  
deploy:
- provider: Environment
  name: halcyon-node-api
